USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60;
USE WAREHOUSE COMPUTE_WH;

-- 1. Source: mimic Openflow PostgreSQL CDC destination table
CREATE DATABASE IF NOT EXISTS DEMO_POC;
CREATE SCHEMA IF NOT EXISTS DEMO_POC.PUBLIC_SRC;
CREATE OR REPLACE TABLE DEMO_POC.PUBLIC_SRC.RESERVATION (
  RESERVATION_ID NUMBER, TENANT_ID VARCHAR, PHONE_NUMBER VARCHAR, CUSTOMER_NAME VARCHAR,
  STATUS VARCHAR, RESERVED_AT TIMESTAMP_NTZ,
  _SNOWFLAKE_INSERTED_AT TIMESTAMP_NTZ, _SNOWFLAKE_UPDATED_AT TIMESTAMP_NTZ, _SNOWFLAKE_DELETED BOOLEAN
) CHANGE_TRACKING = TRUE;

INSERT INTO DEMO_POC.PUBLIC_SRC.RESERVATION
SELECT SEQ4()+1,
       IFF(MOD(SEQ4(),2)=0,'TENANT_A','TENANT_B'),
       '090-0000-' || LPAD(MOD(SEQ4(),1000)::VARCHAR,4,'0'),
       'Customer ' || SEQ4(),
       'BOOKED',
       DATEADD(minute, SEQ4(), '2026-10-01'::TIMESTAMP_NTZ),
       SYSDATE(), SYSDATE(), FALSE
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

-- 2. Application package + shared content
CREATE APPLICATION PACKAGE IF NOT EXISTS DEMO_HT_PKG;
CREATE SCHEMA IF NOT EXISTS DEMO_HT_PKG.SHARED_SCHEMA;
CREATE SCHEMA IF NOT EXISTS DEMO_HT_PKG.STAGE_SCHEMA;
CREATE STAGE IF NOT EXISTS DEMO_HT_PKG.STAGE_SCHEMA.APP_STAGE;

GRANT REFERENCE_USAGE ON DATABASE DEMO_POC TO SHARE IN APPLICATION PACKAGE DEMO_HT_PKG;
CREATE OR REPLACE VIEW DEMO_HT_PKG.SHARED_SCHEMA.RESERVATION AS
  SELECT * FROM DEMO_POC.PUBLIC_SRC.RESERVATION;
GRANT USAGE ON SCHEMA DEMO_HT_PKG.SHARED_SCHEMA TO SHARE IN APPLICATION PACKAGE DEMO_HT_PKG;
GRANT SELECT ON VIEW DEMO_HT_PKG.SHARED_SCHEMA.RESERVATION TO SHARE IN APPLICATION PACKAGE DEMO_HT_PKG;
