-- Provider account: upload app files, register version, test-install in provider account (dev/test)
-- Run from repository root:  snow sql -c <provider_conn> -f 02_provider_build_and_test.sql
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

PUT file://app/manifest.yml              @DEMO_HT_PKG.STAGE_SCHEMA.APP_STAGE/v1           AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://app/setup.sql                 @DEMO_HT_PKG.STAGE_SCHEMA.APP_STAGE/v1           AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://app/README.md                 @DEMO_HT_PKG.STAGE_SCHEMA.APP_STAGE/v1           AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://app/streamlit/app.py          @DEMO_HT_PKG.STAGE_SCHEMA.APP_STAGE/v1/streamlit AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://app/streamlit/environment.yml @DEMO_HT_PKG.STAGE_SCHEMA.APP_STAGE/v1/streamlit AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

ALTER APPLICATION PACKAGE DEMO_HT_PKG REGISTER VERSION V1 USING '@DEMO_HT_PKG.STAGE_SCHEMA.APP_STAGE/v1';

-- test install in the provider account (this is NOT the consumer install)
CREATE APPLICATION DEMO_HT_APP_TEST FROM APPLICATION PACKAGE DEMO_HT_PKG USING VERSION V1;

-- warehouse referenced by the in-app agent (name is fixed in setup.sql)
CREATE WAREHOUSE IF NOT EXISTS HT_APP_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT EXECUTE TASK, EXECUTE MANAGED TASK ON ACCOUNT TO APPLICATION DEMO_HT_APP_TEST;
GRANT USAGE        ON WAREHOUSE HT_APP_WH TO APPLICATION DEMO_HT_APP_TEST;  -- Streamlit -> agent (app identity)
GRANT CALLER USAGE ON WAREHOUSE HT_APP_WH TO APPLICATION DEMO_HT_APP_TEST;  -- CoWork / REST / SQL (restricted caller's rights)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO APPLICATION DEMO_HT_APP_TEST;   -- Streamlit -> DATA_AGENT_RUN (app identity)
CALL DEMO_HT_APP_TEST.api.init();

-- checks
SELECT COUNT(*) FROM DEMO_HT_APP_TEST.api.reservation_v;
CALL DEMO_HT_APP_TEST.api.lookup_by_phone('090-0000-0001');
DESC AGENT DEMO_HT_APP_TEST.AGENT.RESERVATION_AGENT;
SELECT SNOWFLAKE.CORTEX.DATA_AGENT_RUN('DEMO_HT_APP_TEST.AGENT.RESERVATION_AGENT',
  '{"messages":[{"role":"user","content":[{"type":"text","text":"090-0000-0001 の予約を最新5件教えて"}]}]}');

-- change source data, then wait ~1 min and re-run the checks above
-- UPDATE DEMO_POC.PUBLIC_SRC.RESERVATION SET STATUS='CANCELLED', _SNOWFLAKE_UPDATED_AT=SYSDATE() WHERE RESERVATION_ID=2;
-- UPDATE DEMO_POC.PUBLIC_SRC.RESERVATION SET _SNOWFLAKE_DELETED=TRUE, _SNOWFLAKE_UPDATED_AT=SYSDATE() WHERE RESERVATION_ID=1002;
