-- consumer account (<CONSUMER_ORG>.<CONSUMER_ACCOUNT>) で ACCOUNTADMIN として実行
USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60;
USE WAREHOUSE COMPUTE_WH;

-- 1. リスティングからアプリをインストール
CREATE APPLICATION DEMO_HT_APP FROM LISTING <LISTING_GLOBAL_NAME>;

-- 2. 権限付与（同期タスク + Agent のツール実行用ウェアハウス）
GRANT EXECUTE TASK, EXECUTE MANAGED TASK ON ACCOUNT TO APPLICATION DEMO_HT_APP;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO APPLICATION DEMO_HT_APP;

-- 3. 初期ロード + 同期タスク開始 + アプリ内 Agent 作成
CALL DEMO_HT_APP.api.init('COMPUTE_WH');

-- 4. 動作確認
SELECT COUNT(*) FROM DEMO_HT_APP.api.reservation_v;
SHOW STREAMLITS IN APPLICATION DEMO_HT_APP;
-- Snowsight: Data Products » Apps » DEMO_HT_APP » DEMO_UI を開く
